name: 🛠️ Builds
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.runner }}
        name: ${{ matrix.name }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - identifier: linux-release
                      name: Linux Release
                      runner: ubuntu-20.04
                      target: template_release
                      platform: linux
                      arch: x86_64
                    - identifier: windows-release
                      name: Windows Release
                      runner: windows-latest
                      target: template_release
                      platform: windows
                      arch: x86_64
                    - identifier: macos-release
                      name: macOS (universal) Release
                      runner: macos-latest
                      target: template_release
                      platform: macos
                      arch: universal

        steps:
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Set up SCons
              shell: bash
              run: |
                  python -c "import sys; print(sys.version)"
                  python -m pip install scons
                  scons --version

            - name: Checkout project
              uses: actions/checkout@v3
              with:
                  submodules: false

            - name: Checkout godot-cpp
              uses: actions/checkout@v3
              with:
                  repository: godotengine/godot-cpp
                  path: godot-cpp
                  submodules: recursive

            - name: Checkout private Discord GameSDK mirror repo
              uses: actions/checkout@v3
              with:
                  token: "${{secrets.DISCORD_SDK_MIRROR_PAT}}"
                  repository: 3ddelano/discord_game_sdk_mirror
                  path: thirdparty/discord_game_sdk
                  ref: "main"

            - name: (Windows) Install mingw64
              if: ${{ matrix.platform == 'windows' }}
              shell: sh
              run: |
                  sudo apt-get install mingw-w64
                  sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
                  sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

            - name: (Linux) Install dependencies
              if: ${{ matrix.platform == 'linux' }}
              run: |
                  sudo apt-get update -qq
                  sudo apt-get install -qqq build-essential pkg-config

            - name: Compile godot-cpp
              shell: sh
              working-directory: godot-cpp
              run: |
                  scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}'

            - name: Run setup.py
              shell: sh
              run: |
                  python setup.py

            - name: Compile extension
              shell: sh
              run: |
                  scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }} dev_build=no'

            - name: (Windows) Delete compilation files
              if: ${{ matrix.platform == 'windows' }}
              run: |
                  Remove-Item sample/addons/discord-game-sdk-godot/bin/* -Include *.exp,*.lib,*.pdb,*.ilk -Force

            - name: Copy extra files to addon folder
              shell: sh
              run: |
                  cp --no-clobber '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.md' '${{ github.workspace }}/sample/addons/discord-game-sdk-godot/'

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ github.event.repository.name }}
                  path: |
                      ${{ github.workspace }}/sample/addons/*

            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.1
              with:
                  type: "zip"
                  filename: "discord_game_sdk_godot.${{ matrix.platform }}.${{ matrix.arch }}.zip"
                  path: "${{ github.workspace }}/sample/addons/discord-game-sdk-godot/bin/"
                  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: ${{ github.event.repository.name }}
                  path: ${{ github.workspace }}/sample/addons/discord-game-sdk-godot
